// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
	"storage/config"
	"storage/internal/biz"
	"storage/internal/data"
	"storage/internal/server"
	"storage/internal/service"
)

// Injectors from wire.go:

func initApp(localStorageConfig config.LocalStorage) *gin.Engine {
	dataData := data.NewData(localStorageConfig)
	storageInterface := data.NewStorageRepo(dataData)
	storageUseCase := biz.NewStorageUseCase(storageInterface)
	storageService := service.NewStorageService(storageUseCase)
	engine := server.NewHTTPServer(storageService)
	return engine
}
